<?php
  function loginart_menu() {
    $items['loginchoice'] = array(
      'title' => 'Start Browsing!',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('intro_choice'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    $items['browse'] = array(
      'title' => 'Browse',
      'page callback' => 'gallery1',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  function loginart_user_login(&$edit, $account) {
    $_GET['destination'] = 'loginchoice';
  }

  function intro_choice() {
    //(Show comparison view?)
    // $current_view = views_get_view('art_comparison');
    // $current_view->display['art_comparison']->display_options['enabled'] = TRUE;
    // views_save_view($current_view);

    //Load first two images as choices to compare
    $artpiece1_nid = 1;
    $artpiece1_node = node_load($artpiece1_nid);

    $artpiece1_imagepath = image_style_url('art-compares', $artpiece1_node->field_artwork_image[$artpiece1_node->language][0]['uri']);

    $artpiece2_nid = 2;
    $artpiece2_node = node_load($artpiece2_nid);


    $form['choice'] = array(
      '#title' => 'Pick Your Favorite',
      '#type' => 'radios',
      '#options' => array(
        '<img class="art-compares" src="' . file_create_url($artpiece1_node->field_artwork_image['und'][0]['uri']) . '">',
        '<img class="art-compares" src="' . file_create_url($artpiece2_node->field_artwork_image['und'][0]['uri']) . '">',
      ),
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Save my choice!'
    );
    return $form;
  }

  function intro_choice_submit($form, &$form_state) {
    $form_state['redirect'] = 'browse';
  }

  function gallery1() {
    return '<p>Gallery1</p>';
  }
