<?php
  function customize_menu() {
    $items['customize'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('customize_quiz'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    $items['quiz2'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('quiz_2'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    $items['quiz3'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('quiz_3'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    $items['results'] = array(
      'page callback' => 'art_query',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  function customize_quiz() {
    $options = array(
      'headers' => array(
        'client_id' => '6265',
        'client_secret' => '144e2602cbd778cc9bb213976ea3fe4e',
        'grant_type' => 'client_credentials',
      ),
      'method' => 'GET',
      'max_redirects' => 3,
      'timeout' => 30.0,
      'context' => NULL,
    );

    $token_call = 'https://www.deviantart.com/oauth2/token?client_id=6265&client_secret=144e2602cbd778cc9bb213976ea3fe4e&grant_type=client_credentials';

    $response = drupal_http_request($token_call, $options);
    $result_array = json_decode($response->data, TRUE);
    $_SESSION['access_token'] = $result_array['access_token'];

    $_SESSION['user_tags'] = array();
    $artpiece22_node = node_load(22);
    $artpiece27_node = node_load(27);

    $firstoptions = array(
      '<img class="art-quiz" src="' . file_create_url($artpiece22_node->field_artwork_image['und'][0]['uri']) . '">',
      '<img class="art-quiz" src="' . file_create_url($artpiece27_node->field_artwork_image['und'][0]['uri']) . '">',
    );

    $form['choice'] = array(
      '#title' => 'I prefer:',
      '#type' => 'radios',
      '#options' => $firstoptions,
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Next'
    );
    return $form;
  }

  function customize_quiz_submit($form, &$form_state) {
    $_SESSION['first_choice'] = $form_state['values']['choice'];
    $form_state['redirect'] = 'quiz2';
  }

  function quiz_2() {
    if ($_SESSION['first_choice'] == 0) {
      $artpiece1_node = node_load(32);
      $artpiece2_node = node_load(31);
      array_push($_SESSION['user_tags'], 'landscape');
    } else if ($_SESSION['first_choice'] == 1){
      $artpiece1_node = node_load(25);
      $artpiece2_node = node_load(20);
      array_push($_SESSION['user_tags'], 'portrait');
    }

    $secondoptions = array(
      '<img class="art-quiz" src="' . file_create_url($artpiece1_node->field_artwork_image['und'][0]['uri']) . '">',
      '<img class="art-quiz" src="' . file_create_url($artpiece2_node->field_artwork_image['und'][0]['uri']) . '">',
    );

    $form['choice2'] = array(
      '#title' => 'I prefer:',
      '#type' => 'radios',
      '#options' => $secondoptions,
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Next'
    );
    return $form;
  }

  function quiz_2_submit($form, &$form_state) {
    $_SESSION['second_choice'] = $form_state['values']['choice2'];
    $form_state['redirect'] = 'quiz3';
  }

  function quiz_3() {
    if ($_SESSION['first_choice'] == 0 && $_SESSION['second_choice'] == 0) {
      $artpiece1_node = node_load(18);
      $artpiece2_node = node_load(30);
      array_push($_SESSION['user_tags'], 'colorful');
    } else if ($_SESSION['first_choice'] == 0 && $_SESSION['second_choice'] == 1) {
      $artpiece1_node = node_load(21);
      $artpiece2_node = node_load(23);
      array_push($_SESSION['user_tags'], 'majestic');
    } else if ($_SESSION['first_choice'] == 1 && $_SESSION['second_choice'] == 0) {
      $artpiece1_node = node_load(21);
      $artpiece2_node = node_load(19);
      array_push($_SESSION['user_tags'], 'stylized');
    } else if ($_SESSION['first_choice'] == 1 && $_SESSION['second_choice'] == 1) {
      $artpiece1_node = node_load(24);
      $artpiece2_node = node_load(16);
      array_push($_SESSION['user_tags'], 'anime');
    }

    $thirdoptions = array(
      '<img class="art-quiz" src="' . file_create_url($artpiece1_node->field_artwork_image['und'][0]['uri']) . '">',
      '<img class="art-quiz" src="' . file_create_url($artpiece2_node->field_artwork_image['und'][0]['uri']) . '">',
    );

    $form['choice3'] = array(
      '#title' => 'I prefer:',
      '#type' => 'radios',
      '#options' => $thirdoptions,
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Next'
    );
    return $form;
  }

  function quiz_3_submit($form, &$form_state) {
    $_SESSION['third_choice'] = $form_state['values']['choice3'];
    if ($_SESSION['first_choice'] == 0 && $_SESSION['second_choice'] == 0 && $_SESSION['third_choice'] == 0) {
      array_push($_SESSION['user_tags'], 'illustration');
    } else if ($_SESSION['first_choice'] == 0 && $_SESSION['second_choice'] == 0 && $_SESSION['third_choice'] == 1) {
      array_push($_SESSION['user_tags'], 'nature');
    } else if ($_SESSION['first_choice'] == 0 && $_SESSION['second_choice'] == 1 && $_SESSION['third_choice'] == 0) {
      array_push($_SESSION['user_tags'], 'illustration');
    } else if ($_SESSION['first_choice'] == 0 && $_SESSION['second_choice'] == 1 && $_SESSION['third_choice'] == 1) {
      array_push($_SESSION['user_tags'], 'bright');
    } else if ($_SESSION['first_choice'] == 1 && $_SESSION['second_choice'] == 0 && $_SESSION['third_choice'] == 0) {
      array_push($_SESSION['user_tags'], 'sketch');
    } else if ($_SESSION['first_choice'] == 1 && $_SESSION['second_choice'] == 0 && $_SESSION['third_choice'] == 1) {
      array_push($_SESSION['user_tags'], 'concept art');
    } else if ($_SESSION['first_choice'] == 1 && $_SESSION['second_choice'] == 1 && $_SESSION['third_choice'] == 0) {
      array_push($_SESSION['user_tags'], 'concept');
    } else if ($_SESSION['first_choice'] == 1 && $_SESSION['second_choice'] == 1 && $_SESSION['third_choice'] == 1) {
      array_push($_SESSION['user_tags'], 'painting');
    }
    $form_state['redirect'] = 'results';
  }

  function art_query() {
    $search_parameter = $_SESSION['user_tags'][(rand(0, 2))];
    $options = array(
      'headers' => array(
        'access_token' => $_SESSION['access_token'],
        'q' => $search_parameter,
        'offset' => '10',
        'limit' => '100',
        'category_path' => 'digitalart/paintings/illustrations',
      ),
      'method' => 'GET',
      'max_redirects' => 3,
      'timeout' => 30.0,
      'context' => NULL,
    );

    $api_call = 'https://www.deviantart.com/api/v1/oauth2/browse/hot?access_token=' . $_SESSION['access_token'] . '&q=' . $search_parameter . '&offset=10&limit=100&category_path=digitalart/paintings/illustrations';

    $response = drupal_http_request($api_call, $options);
    $result_array = json_decode($response->data, TRUE);
    //this works!!!! var_dump($result_array);


    if(empty($result_array['results'] === 'false')) {
      $output = '';
      for ($i = 0; $i < count($result_array['results']); $i++) {
        $title = $result_array['results'][$i]['title'];
        $url = $result_array['results'][$i]['url'];
        $artist = $result_array['results'][$i]['author']['username'];
        $image = $result_array['results'][$i]['preview']['src'];

        $output= $output.
        '<div class="result-image-block">
          <h4><a href=' . $url . '>' . $title . ' by ' . $artist .'</a></h4>
          <img class="image-results" src="'. $image .'">
          </div>';
      }
    } else {
      $output = "Sorry no results";
    }
    return $output;
  }
